### ISSUE TITLE
Shruti Week 9 Review Ticket

### ISSUE THREAD

**Issue by shrutiapcsp** [gigiguan/python#10]
Link to Video:
https://youtu.be/rlFJ5zLz1U8
- [x] Collaboration: HTML, seen by the README (College Board Unit 1.1)
- [x] Program Design and purpose: HTML, seen by wireframes and css of project (College Board Unit 1.3)
- [x] Conditionals: seen by Color Codes page (College Board Unit 3.6)
- [x] Binary/Hexdecimal: seen by Color Codes page (College Board Unit 2.1)

**Comment by jm1021** [comment]
Recap.
1. Collaboration.  Good discussion on README, Tickets, Tasks.   Shows Markdown code.  2/2
2. Program Design and Purpose.  Shared Wires, but also talks on CSS as part of design which is very strong.  Talked about purpose and information for Classes in this section.   I like that this was all considered design and purpose. 2/2
3. Boolean Expressions.  Seemed a little bit random on code review, scrolled around and found a couple of if statements, but did not highlight code that actually calculates color code.   1.25/2

Improvement.   More purpose and preparation is required when showing technical content.  In this section command was questioned.   I see similar comments from teammates.

5.25/6
