### ISSUE TITLE
Jessie Week 9 Review Ticket

### ISSUE THREAD

**Issue by shrutiapcsp** [gigiguan/python#15]
https://www.youtube.com/watch?v=KWv7x374a2Y

- [x] Collaboration (CB Notes, scrumboard commits)
- [x] Boolean Expression and Conditions (seen on Logicgates.html line 16)
- [x] Iteration (loops seen on RGB.html)
- [ ] List/Dictionary

**Comment by jm1021** [comment]
Discussed Collaboration, Logic Gates (conditionals), RBG (loops).  All items showed some understanding and development in work.   Code reviews could have been more detailed on individual tasks, for instance iteration shows RGB values and my contribution was "?".   Another good addition would be to talk about relevance of an Issue with current PBL.   5.25/6

**Comment by jm1021** [comment]
I would like to see more detail (citations) in comments.  if/else comment was more toward colaboration, but most of the comments were brief. 1.5/2
